### ISSUE TITLE
Basic Kubernetes Minio component

### ISSUE THREAD

**Issue by technosophos** [deis/minio#1]
The idea of this project is that we can provide a simple, single-pod S3 object storage system for developers and for light-weight clusters.

The following tasks need to be done to get this project ready for a 0.0.1 release:
- [x] Create a repository that follows the [standard Deis pattern](https://github.com/technosophos/prototype-repo) for Kubernetes components
- [x] Kubernetes service defined
- [x] Kubernetes RC defined, scaling to 1 by default (Minio doesn't yet support multiple replicas)
- [x] Build Minio from source _from the master branch_, and create a Docker image
- [x] Create Minio admin account locally, and then upload the credential as a Kubernetes secret. There should be a Makefile target for this. (#13)
- [x] Create a shared account (Token/Secret) that all other Deis services can use to work with minio, and upload that as a Kubernetes secret. This can use the same Makefile target as the above. (#13)
- [x] Configure Minio to use those secrets in its RC
- [x] Add support for generating an SSL certificate locally, and then storing that in a secret. There should be a Makefile target for this (`make ssl-cert`). Self-signed is fine for now. (https://github.com/deis/minio/pull/15)
- [x] Configure Minio to read the SSL key and cert from the secret and use it in the RC (#17)
- [x] Create a Minio MC pod to be used for testing Minio from within a Kubernetes cluster (#19)
- [x] Write an entry point on the MC pod that will run integration tests against the Minio RC to verify that it is up, running, and correctly configured. (#19)
- [x] Update the README file with information on how to install and configure this package (#14)
- [x] Add an example in the `_docs` directory for accessing and using Minio object storage from another pod. (#14)
- Test this installation on the below installs. It must run on both with no modifications to the underlying environment.
  - [x] Kubernetes + Vagrant (local)
  - [x] GKE

A few guidelines:
- For now, we are not assuming persistent storage. (Later, we will add volumes to the RC to provide that)
- All installation and configuration should be done in the Makefile. No shell scripts unless absolutely necessary.
- All code in the container should be written in Go. If you need a bootstrapping program, it should be called `boot.go`, located in the root of this repository, and when compiled should be placed in `rootfs/bin/boot`.
- As far as is possible, we should be working off of Minio's master branch, not a snapshot of an older version.

**Comment by smothiki** [comment]
Minio is a S3 backed storage for Microservices which supports only one access-key and access-secret. Minio-xl is a petabyte s3 backend storage which supports multiple configurations . I think this should be a different project.

**Comment by harshavardhana** [comment]
Thanks a lot for doing this - In case you guys want to leverage. 

Here is our official docker repo - https://hub.docker.com/r/minio/minio/

https://github.com/minio/minio/blob/master/Docker.md

**Comment by arschles** [comment]
hey @harshavardhana - no problem. this is still very much a work in progress and we'll look at the official repo and see what we can build upon. thanks!

**Comment by harshavardhana** [comment]
> hey @harshavardhana - no problem. this is still very much a work in progress and we'll look at the official repo and see what we can build upon. thanks!

Sure, ping me if any issue.

**Comment by arschles** [comment]
@technosophos why build minio from source on the master branch instead of using a stable release?

**Comment by harshavardhana** [comment]
> @technosophos why build minio from source on the master branch instead of using a stable release?

Just chiming in **my two cents**

We haven't officially made a release yet, we built binaries for general testing and should be considered beta :-).  

We are going to cleanup the server and make an official release later this month and thanks for doing this :-)

**Comment by arschles** [comment]
@technosophos above, you write 'Create Minio admin account locally' and 'Create a shared account (Token/Secret) that all other Deis services can use to work with minio'. Are you saying the build target should generate keys at runtime?

**Comment by arschles** [comment]
@harshavardhana thanks for explaining that - very good background for me to have.

**Comment by arschles** [comment]
note that we have decided that we won't run minio with SSL for alpha. all existing SSL related code to create SSL resources, store them in k8s secrets, run minio with cert and key, configure clients, etc... will remain commented out.

cc/ @technosophos

**Comment by arschles** [comment]
@bacongobbler were you able to test on GKE?

**Comment by arschles** [comment]
closing, as the final bullet (testing on GKE) is complete
